test_data_path: "/home/justin/code/LieNeurons/data/sl3_equiv_5_input_data/sl3_equiv_100_s_05_test_data.npz"
# logger
model_description: "SL3EquivariantFunctionFitting"
print_freq: 100
# model_type: "LN"
# model_path: "/home/justin/code/LieNeurons/weights/0926_platonic_cls_LN_best_test_loss_good.pt"

model_type: "MLP"
model_path: "/home/justin/code/LieNeurons/weights/rebuttal_cls_mlp_aug_4_best_test_acc.pt"
# model_type: "LN_relu_bracket"
# model_path: "/home/justin/code/LieNeurons/weights/rebuttal_cls_rb_5_best_test_acc.pt"

# model_type: "LN_relu"
# model_path: "/home/justin/code/LieNeurons/weights/0928_cls_one_relu_best_test_acc.pt"

# model_type: "LN_bracket"
# model_path: "/home/justin/code/LieNeurons/weights/0928_cls_one_bracket_best_test_acc.pt"

# model_type: "MLP"
# model_path: "/home/justin/code/LieNeurons/weights/0928_cls_MLP_best_test_acc.pt"

# model_type: "LN_bracket_no_residual"
# model_path: "/home/justin/code/LieNeurons/weights/0928_cls_one_bracket_no_residual_best_test_acc.pt"
batch_size: 100
shuffle: False
num_test: 1000
num_rotations: 500
rotation_factor: 0.174533 # 10 degrees
