# train_data_path: "/home/justin/code/LieNeurons/data/sl3_equiv_5_input_data/sl3_equiv_100_s_05_train_data.npz"
# test_data_path: "/home/justin/code/LieNeurons/data/sl3_equiv_5_input_data/sl3_equiv_100_s_05_test_data.npz"
# logger
model_description: "SL3classification"
print_freq: 1
# model_type: "LN_relu_bracket"
# model_save_path: "/home/justin/code/LieNeurons/weights/0928_cls_one_relu_one_bracket"
# log_writer_path: "/home/justin/code/LieNeurons/logs/0928_cls_one_relu_one_bracket"

# model_type: "LN_relu"
# model_save_path: "/home/justin/code/LieNeurons/weights/0928_cls_one_relu"
# log_writer_path: "/home/justin/code/LieNeurons/logs/0928_cls_one_relu"

# model_type: "LN_bracket"
# model_save_path: "/home/justin/code/LieNeurons/weights/0928_cls_one_bracket"
# log_writer_path: "/home/justin/code/LieNeurons/logs/0928_cls_one_bracket"
model_type: "MLP"
model_save_path: "/home/justin/code/LieNeurons/weights/rebuttal_cls_mlp_aug_4"
log_writer_path: "/home/justin/code/LieNeurons/logs/rebuttal_cls_mlp_aug_4"
# model_type: "LN_relu_bracket"
# model_save_path: "/home/justin/code/LieNeurons/weights/rebuttal_cls_rb_5"
# log_writer_path: "/home/justin/code/LieNeurons/logs/rebuttal_cls_rb_5"
resume_training: false
resume_model_path: "/home/justin/code/LieNeurons/weights/0921_sl3_equiv_first_try.pth.tar"
num_workers: 1
batch_size: 100
update_every_batch: 1
# initial_learning_rate: 0.00001
initial_learning_rate: 0.0001
learning_rate_decay_rate: 0.0
weight_decay_rate: 0.00
num_train: 500000
num_test: 1000
shuffle: True
train_augmentation: True
rotation_factor: 0.174533 # 10 degrees
