test_data_path: "/home/justin/code/LieNeurons/data/sl3_equiv_lie_bracket_data/sl3_equiv_10000_lie_bracket_2inputs_test_data.npz"
# logger
model_description: "SL3EquivariantFunctionFitting"
print_freq: 100
# model_type: "LN"
# model_path: "/home/justin/code/LieNeurons/weights/0926_exp_sl3_equiv_lie_bracket_2input_LN_5_256_no_share_nonlin_train_10000_lr_ 0.000003_best_test_loss_acc.pt"

# model_type: "LN_relu_bracket"
# model_path: "/home/justin/code/LieNeurons/weights/0928_equiv_one_relu_one_bracket_final_best_test_loss_acc.pt"
model_type: "MLP"
model_path: "/home/justin/code/LieNeurons/weights/rebuttal_equiv_mlp_augmented_5_best_test_loss_acc.pt"
# model_type: "MLP"
# model_path: "/home/justin/code/LieNeurons/weights/rebuttal_equiv_mlp_augmented_5_best_test_loss_acc.pt"
# model_type: "MLP"
# model_path: "/home/justin/code/LieNeurons/weights/0928_equiv_MLP_best_test_loss_acc.pt"

# model_type: "LN_bracket_no_residual"
# model_path: "/home/justin/code/LieNeurons/weights/0928_equiv_one_bracket_no_residual_best_test_loss_acc.pt"
batch_size: 100
shuffle: False
