# train_data_path: "/home/justin/code/LieNeurons/data/sl3_equiv_lie_bracket_data/sl3_equiv_10000_lie_bracket_2inputs_augmented_train_data.npz"
# test_data_path: "/home/justin/code/LieNeurons/data/sl3_equiv_lie_bracket_data/sl3_equiv_10000_lie_bracket_2inputs_test_data.npz"
train_data_path: "/home/justin/code/LieNeurons/data/sl3_equiv_lie_bracket_data/sl3_equiv_10000_lie_bracket_2inputs_train_data.npz"
test_data_path: "/home/justin/code/LieNeurons/data/sl3_equiv_lie_bracket_data/sl3_equiv_10000_lie_bracket_2inputs_test_data.npz"
# train_data_path: "/home/justin/code/LieNeurons/data/sl3_equiv_lie_bracket_data/sl3_equiv_10000_lie_bracket_2inputs_augmented_train_data.npz"
# test_data_path: "/home/justin/code/LieNeurons/data/sl3_equiv_lie_bracket_data/sl3_equiv_10000_lie_bracket_2inputs_test_data.npz"
# logger
model_description: "SL3EquivariantFunctionFitting"
print_freq: 100
# model_type: "LN_relu_bracket"
# model_save_path: "/home/justin/code/LieNeurons/weights/1119_equiv_one_relu_one_bracket_final"
# log_writer_path: "/home/justin/code/LieNeurons/logs/1119_equiv_one_relu_one_bracket_final"

# model_type: "LN_relu"
# model_save_path: "/home/justin/code/LieNeurons/weights/1119_equiv_one_relu"
# log_writer_path: "/home/justin/code/LieNeurons/logs/1119_equiv_one_relu"

# model_type: "LN_bracket"
# model_save_path: "/home/justin/code/LieNeurons/weights/1119_equiv_one_bracket_3"
# log_writer_path: "/home/justin/code/LieNeurons/logs/1119_equiv_one_bracket_3"

# model_type: "MLP"
# model_save_path: "/home/justin/code/LieNeurons/weights/rebuttal_equiv_mlp_augmented_5"
# log_writer_path: "/home/justin/code/LieNeurons/logs/rebuttal_equiv_mlp_augmented_5"

model_type: "LN_bracket_no_residual"
model_save_path: "/home/justin/code/LieNeurons/weights/0404_equiv_one_bracket_no_residual_test"
log_writer_path: "/home/justin/code/LieNeurons/logs/0404_equiv_one_bracket_no_residual_test"

resume_training: false
resume_model_path: "/home/justin/code/LieNeurons/weights/0921_sl3_equiv_first_try.pth.tar"
num_workers: 1
batch_size: 100
update_every_batch: 1
# initial_learning_rate: 0.0001
# initial_learning_rate: 0.000003 
# initial_learning_rate: 0.000001
initial_learning_rate: 0.00001
learning_rate_decay_rate: 0.0
weight_decay_rate: 0.00
num_epochs: 1500
shuffle: True
