test_data_path: "/home/justin/code/LieNeurons/data/so3_bch_data/so3_bch_10000_test_data.npz"
# logger
model_description: "SO3BCHFunctionFitting"
print_freq: 100

# model_type: "LN_relu_bracket"
# model_path: "/home/justin/code/LieNeurons/weights/0120_so3_bch_relu_bracket_best_test_loss_acc.pt"

# model_type: "LN_relu"
# model_path: "/home/justin/code/LieNeurons/weights/0120_so3_bch_relu_4_layers_1024"

# model_type: "LN_bracket"
# model_path: "/home/justin/code/LieNeurons/weights/0124_so3_bch_bracket_best_test_loss_acc.pt"

# model_type: "MLP"
# model_path: "/home/justin/code/LieNeurons/weights/0327_so3_bch_mlp_4_layers_1024_augmented_best_test_loss_acc.pt"

# model_type: "EMLP"
# model_path: "/home/justin/code/LieNeurons/weights/EMLP_best_test_loss_acc.pt"

# model_type: "e3nn_norm"
# model_path: "/home/justin/code/LieNeurons/weights/0404_BCH_e3nn_norm_256_best_test_loss_acc.pt"

model_type: "e3nn_s2grid"
model_path: "/home/justin/code/LieNeurons/weights/0404_BCH_e3nn_s2grid_best_test_loss_acc.pt"

batch_size: 1
shuffle: False

calculate_eq_approx_error: False