train_data_path: "/home/justin/code/LieNeurons/data/so3_bch_data/so3_bch_10000_train_data.npz"
# train_data_path: "/home/justin/code/LieNeurons/data/so3_bch_data/so3_bch_10000_augmented_train_data.npz"
test_data_path: "/home/justin/code/LieNeurons/data/so3_bch_data/so3_bch_10000_test_data.npz"
# train_data_path: "/home/justin/code/LieNeurons/data/so3_bch_data/so3_bch_10000_approx_no_conj_train_data.npz"
# test_data_path: "/home/justin/code/LieNeurons/data/so3_bch_data/so3_bch_10000_approx_no_conj_test_data.npz"

# logger
model_description: "SO3 BCH 10000"
print_freq: 100
# model_type: "LN_relu_bracket"
# model_save_path: "/home/justin/code/LieNeurons/weights/0125_so3_bch_relu_bracket"
# log_writer_path: "/home/justin/code/LieNeurons/logs/0125_so3_bch_relu_bracket"

# model_type: "LN_relu"
# model_save_path: "/home/justin/code/LieNeurons/weights/0120_so3_bch_relu_4_layers_1024"
# log_writer_path: "/home/justin/code/LieNeurons/logs/0120_so3_bch_relu_4_layers_1024"

# model_type: "LN_bracket"
# model_save_path: "/home/justin/code/LieNeurons/weights/0124_so3_bch_bracket"
# log_writer_path: "/home/justin/code/LieNeurons/logs/0124_so3_bch_bracket"

# model_type: "MLP"
# model_save_path: "/home/justin/code/LieNeurons/weights/0327_so3_bch_mlp_4_layers_1024_augmented"
# log_writer_path: "/home/justin/code/LieNeurons/logs/0327_so3_bch_mlp_4_layers_1024_augmented"

# model_type: "LN_bracket_no_residual"
# model_save_path: "/home/justin/code/LieNeurons/weights/0928_equiv_one_bracket_no_residual"
# log_writer_path: "/home/justin/code/LieNeurons/logs/0928_equiv_one_bracket_no_residual"

# model_type: "EMLP"
# model_save_path: "/home/justin/code/LieNeurons/weights/0326_BCH_EMLP_512_test"
# log_writer_path: "/home/justin/code/LieNeurons/logs/0326_BCH_EMLP_512_test"

# model_type: "e3nn_norm"
# model_save_path: "/home/justin/code/LieNeurons/weights/0404_BCH_e3nn_norm_1024"
# log_writer_path: "/home/justin/code/LieNeurons/logs/0404_BCH_e3nn_norm_1024"

model_type: "e3nn_s2grid"
model_save_path: "/home/justin/code/LieNeurons/weights/0404_BCH_e3nn_s2grid_small_lr"
log_writer_path: "/home/justin/code/LieNeurons/logs/0404_BCH_e3nn_s2grid_small_lr"

# model_type: "VN_relu"
# model_save_path: "/home/justin/code/LieNeurons/weights/0327_BCH_VN"
# log_writer_path: "/home/justin/code/LieNeurons/logs/0327_BCH_VN"

resume_training: False
resume_model_path: "/home/justin/code/LieNeurons/weights/0326_BCH_EMLP_512_test_best_test_loss_acc.pt"

num_workers: 1
batch_size: 100
update_every_batch: 1
initial_learning_rate: 0.0001
# initial_learning_rate: 0.000003 
# initial_learning_rate: 0.00001
# initial_learning_rate: 0.0005    # EMLP
learning_rate_decay_rate: 0.0
weight_decay_rate: 0.00
num_epochs: 10000
shuffle: True
full_eval_during_training: False
